services:
  akane-next:
    build:
      context: packages/akane-next
      dockerfile: ../../docker/akane-next/Dockerfile
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
      - "5555:5555" # for prisma studio
    develop:
      watch:
        - action: sync
          path: ./packages/akane-next
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
  nginx:
    image: nginx:latest
    build:
      context: docker/nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: akane
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/mysql:/var/lib/mysql
