services:
  akane-next:
    build:
      context: packages/akane-next
      dockerfile: ../../docker/akane-next/Dockerfile
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./packages/akane-next
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
