services:
  akane-next:
    build:
      context: packages/akane-next
      dockerfile: ../../docker/akane-next/Dockerfile
      target: development
      args:
        NODE_ENV: development
        DATABASE_URL: "mysql://root@db:3306/akane"
        MAPBOX_MAP_STYLE: ""
        MAPBOX_ACCESS_TOKEN: ""
    init: true
    command: ["npm", "run", "dev"]
    ports:
      - "3800:3000"
      - "5555:5555" # for prisma studio
    develop:
      watch:
        - action: sync
          path: ./packages/akane-next
          target: /app
          ignore:
            - node_modules
            - .next
        - action: rebuild
          path: package.json
    environment:
      DATABASE_URL: "mysql://root@db:3306/akane"

  nginx:
    build:
      context: docker/nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - akane-next

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: akane
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/mysql:/var/lib/mysql
