services:
  akane-next:
    build:
      context: .
      dockerfile: ./docker/akane-next/Dockerfile
      target: development
      args:
        DATABASE_URL: "mysql://root@db:3306/akane"
        MAPBOX_MAP_STYLE: "mapbox://styles/nenrin/cm77whskd00sl01reh909h23j"
        MAPBOX_ACCESS_TOKEN: "pk.eyJ1IjoibmVucmluIiwiYSI6ImNtNzV1d3hoNTBpanoya3B2d3N0cGNtaTAifQ.8f7ecF34J0Zj0gdDrmaaVA"
    init: true
    ports:
      - "3800:3000"
      - "5555:5555" # for prisma studio
    develop:
      watch:
        - action: sync
          path: ./packages/akane-next
          target: /app/packages/akane-next
          ignore:
            - node_modules
            - .next
        - action: rebuild
          path: package.json
    environment:
      DATABASE_URL: "mysql://root@db:3306/akane"
    depends_on:
      - db

  nginx:
    build:
      context: docker/nginx
      dockerfile: ./Dockerfile
    ports:
      - "443:443"
    depends_on:
      - akane-next

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: akane
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/mysql:/var/lib/mysql
