version: "3"

tasks:
  up:
    desc: 開発サーバーを起動します
    cmds:
      - docker compose up -w

  down:
    desc: 開発サーバーを停止します
    cmds:
      - docker compose down --remove-orphans

  build:
    desc: 開発サーバーのイメージをビルドします
    cmds:
      - docker compose build

  # akane-next に対して npm コマンドを実行するタスク
  # workspace 指定が面倒なのでその shorthand として定義
  # e.g. task nan -- install -D vitest
  npm:akane-next:
    desc: npm コマンドを実行します
    aliases:
      - nan
    cmds:
      - npm -w packages/akane-next {{ .CLI_ARGS }}
