version: "3"

tasks:
  up:
    desc: 開発サーバーを起動します
    cmds:
      - docker compose up -w

  down:
    desc: 開発サーバーを停止します
    cmds:
      - docker compose down --remove-orphans

  build:
    desc: 開発サーバーのイメージをビルドします
    cmds:
      - docker compose build
