import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { WithApolloProvider } from "@/graphql/provider";
import { LocationProvider } from "@/context/LocationContext";
import { MapProvider } from "@/context/MapContext";
import { BottomSheetProvider } from "@/context/BottomSheetContext";
import { Box } from "@chakra-ui/react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body>
        <WithApolloProvider>
          <Provider>
            <MapProvider>
              <LocationProvider>
                <BottomSheetProvider>
                  <Box
                    pos="relative"
                    h="100vh"
                    w="100vw"
                    overflow="hidden"
                  >
                    {children}
                  </Box>
                </BottomSheetProvider>
              </LocationProvider>
            </MapProvider>
          </Provider>
        </WithApolloProvider>
      </body>
    </html>
  );
}
