#!/bin/bash

# このScriptの引数
GHCR_USER=$1
GHCR_TOKEN=$2

cd $(git rev-parse --show-toplevel)/production

echo "[1/4] Login to GitHub Container Registry..."
echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USER --password-stdin

echo "[2/4] Pulling images..."
docker compose pull

echo "[3/4] Stopping containers..."
docker compose down

echo "[4/4] Restarting containers..."
docker compose up -d
