name: akane-next-test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "packages/akane-next/**"
      - ".github/workflows/akane-next-test.yaml"
      - "docker/akane-next/**"
      - "compose.yaml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci -w packages/akane-next
      - name: Generate Prisma
        run: npm run prisma:generate -w packages/akane-next
      - name: Type check
        run: npm run typecheck -w packages/akane-next
      - name: Lint
        run: npm run lint -w packages/akane-next
      - name: Test
        run: npm run test -w packages/akane-next
      - name: Build
        run: npm run build -w packages/akane-next
