name: akane-deploy-production

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  deploy:
    name: Auto Deploy as Production Environment
    runs-on: ubuntu-latest
    steps:
      - name: Setup Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_PRIVATE_KEY }}
          script: |
            cd ~/yaken/2025_9 && git pull
            . ~/yaken/2025_9/production/script/deploy ${{ secrets.GHCR_USER }} ${{ secrets.GHCR_TOKEN }}
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.RELEASE_NOTIFY_WEBHOOK }}
          content: "@here\n# :tada:リリースされました！\nURL: https://akane.yaken.org/"
